#ifndef BicolaDL.h  //ARCHIVO DE CABECERA
#define BicolaDL.h

#include <stdbool.h>    //BIBLIOTECA BOOLEANOS

typedef int DATO;   //ALIAS PARA LA IFORMACIÓN DEL NODO

typedef struct _NODO NODO;  //ALIAS DE LA ESTRUCTURA DEL NODO
struct _NODO{   //ESTRUCTURA DEL NODO
    DATO info;  //INFORAMACIÓN DEL NODO
    NODO *siguiente;    //APUNTADOR/ENLACE DEL NODO AL SIGUIENTE ELEMENTO DE LA LISTA
    NODO *anterior;     //APUNTADOR/ENLACE DEL NODO AL ANTERIOR ELEMENTO DE LA LISTA
};

typedef struct _BICOLADL BICOLADL;  //ALIAS DE LA ESTRUCTURA LISTA
struct _BICOLADL{  //ESTRUCTURA DE LA LISTA
    NODO *head; //APUNTADOR/ENLACE A LA CABEZA DE LA LISTA
    NODO *tail; //APUNTADOR/ENLACE A LA COLA DE LA LISTA
    int num;    //CONTADOR DE ELEMENTOS DE LA LISTA
};

NODO* crearNodo(DATO n);    //PROTOTIPO DE LA FUNCIÓN PARA CREAR UN NODO, RETORNA UN APUNTADOR TIPO NODO
void liberarNodo(NODO *n);  //PROTOTIPO DE LA FUNCIÓN PARA LIBERAR UN NODO
BICOLADL* crearBicolaDL();    //PROTOTIPO DE LA FUNCIÓN PARA CREAR UNA LISTA, RETORNA UN APUNTADOR TIPO LISTA
void liberarBicolaDL(BICOLADL *l);    //PROTOTIPO DE LA FUNCIÓN PARA LIBERAR UNA LISTA

bool insertarInicioDL(BICOLADL *l, DATO n);  //PROTOTIPO DE LA FUNCIÓN PARA INSETAR UN ELEMENTO AL INICIO DE LA LISTA
bool insertarFinalDL(BICOLADL *l, DATO n);   //PROTOTIPO DE LA FUNCIÓN PARA INSERTAR UN ELEMENTO AL FINAL DE LA LISTA

void eliminarInicioDL(BICOLADL *l);  //PROTOTIPO DE LA FUNCIÓN PARA ELIMINAR UN ELEMENTO AL INCIO DE LA LISTA
void eliminarFinalDL(BICOLADL *l);   //PROTOTIPO DE LA FUNCIÓN PARA ELIMINAR UN ELEMENTO AL FINAL DE LA LISTA

bool esVaciaDL(BICOLADL *l); //PROTOTIPO DE LA FUNCIÓN PARA DETERNIMAR SI LA LISTA ESTÁ VACÍA
bool vaciarBicolaDL(BICOLADL *l); //PROTOTIPO DE LA FUNCIÓN PARA VACIAR LA LISTA

void imprimirBicolaDL(BICOLADL *l);   //PROTOTIPO DE LA FUNCIÓN PARA IMPRIMIR LA LISTA
DATO* recuperarCabeza(BICOLADL *l); //PROTOTIPO DE LA FUNCIÓN PARA RETORNAR LA DIRECCIÓN DE MEMORIA DE CABEZA DE LA BICOLA
DATO* recuperarCola(BICOLADL *l); //PROTOTIPO DE LA FUNCIÓN PARA RETORNAR LA DIRECCIÓN DE MEMORIA DE COLA DE LA BICOLA

#endif // BicolaDL

